var annotated_dup =
[
    [ "z0", null, [
      [ "Application", "classz0_1_1_application.html", "classz0_1_1_application" ],
      [ "ApplicationConfig", "structz0_1_1_application_config.html", "structz0_1_1_application_config" ],
      [ "BoxShape", "classz0_1_1_box_shape.html", null ],
      [ "Buffer", "classz0_1_1_buffer.html", null ],
      [ "Color", "structz0_1_1_color.html", "structz0_1_1_color" ],
      [ "ConvexHullShape", "classz0_1_1_convex_hull_shape.html", null ],
      [ "Cubemap", "classz0_1_1_cubemap.html", null ],
      [ "DescriptorPool", "classz0_1_1_descriptor_pool.html", null ],
      [ "DescriptorSetLayout", "classz0_1_1_descriptor_set_layout.html", null ],
      [ "DescriptorWriter", "classz0_1_1_descriptor_writer.html", null ],
      [ "Device", "classz0_1_1_device.html", null ],
      [ "Font", "classz0_1_1_font.html", "classz0_1_1_font" ],
      [ "GEvent", "classz0_1_1_g_event.html", null ],
      [ "GEventClick", "structz0_1_1_g_event_click.html", "structz0_1_1_g_event_click" ],
      [ "GEventKeyb", "structz0_1_1_g_event_keyb.html", "structz0_1_1_g_event_keyb" ],
      [ "GEventMouse", "structz0_1_1_g_event_mouse.html", "structz0_1_1_g_event_mouse" ],
      [ "GEventState", "structz0_1_1_g_event_state.html", "structz0_1_1_g_event_state" ],
      [ "GManager", "classz0_1_1_g_manager.html", "classz0_1_1_g_manager" ],
      [ "GText", "classz0_1_1_g_text.html", "classz0_1_1_g_text" ],
      [ "GWidget", "classz0_1_1_g_widget.html", "classz0_1_1_g_widget" ],
      [ "GWindow", "classz0_1_1_g_window.html", "classz0_1_1_g_window" ],
      [ "Image", "classz0_1_1_image.html", "classz0_1_1_image" ],
      [ "ImageTexture", "classz0_1_1_image_texture.html", "classz0_1_1_image_texture" ],
      [ "Input", "classz0_1_1_input.html", null ],
      [ "InputEvent", "classz0_1_1_input_event.html", "classz0_1_1_input_event" ],
      [ "InputEventGamepadButton", "classz0_1_1_input_event_gamepad_button.html", "classz0_1_1_input_event_gamepad_button" ],
      [ "InputEventKey", "classz0_1_1_input_event_key.html", "classz0_1_1_input_event_key" ],
      [ "InputEventMouseButton", "classz0_1_1_input_event_mouse_button.html", "classz0_1_1_input_event_mouse_button" ],
      [ "InputEventMouseMotion", "classz0_1_1_input_event_mouse_motion.html", "classz0_1_1_input_event_mouse_motion" ],
      [ "Loader", "classz0_1_1_loader.html", null ],
      [ "Material", "classz0_1_1_material.html", null ],
      [ "Mesh", "classz0_1_1_mesh.html", null ],
      [ "Node", "classz0_1_1_node.html", "classz0_1_1_node" ],
      [ "Object", "classz0_1_1_object.html", "classz0_1_1_object" ],
      [ "OutlineMaterials", "classz0_1_1_outline_materials.html", null ],
      [ "Rect", "structz0_1_1_rect.html", "structz0_1_1_rect" ],
      [ "Resource", "classz0_1_1_resource.html", "classz0_1_1_resource" ],
      [ "Shader", "classz0_1_1_shader.html", null ],
      [ "ShaderMaterial", "classz0_1_1_shader_material.html", null ],
      [ "Shape", "classz0_1_1_shape.html", null ],
      [ "Signal", "classz0_1_1_signal.html", "classz0_1_1_signal" ],
      [ "StandardMaterial", "classz0_1_1_standard_material.html", null ],
      [ "StaticCompoundShape", "classz0_1_1_static_compound_shape.html", null ],
      [ "SubShape", "structz0_1_1_sub_shape.html", null ],
      [ "Surface", "structz0_1_1_surface.html", null ],
      [ "Texture", "classz0_1_1_texture.html", "classz0_1_1_texture" ],
      [ "Vertex", "structz0_1_1_vertex.html", null ],
      [ "Window", "classz0_1_1_window.html", "classz0_1_1_window" ]
    ] ]
];